Build TNS Report Form Module for TOM Toolkit
TOMToolkit/tom_tns pull request #1
Opened 2023-11-17 01:11 UTC by jchate6

This PR should result in an alpha Version of the TOM TNS report app that allows users to report new objects and send classifications to the TNS.

Users will need to make their own bots to do this.

It draws on the TNS report forms developed by [Saguaro TOM](https://github.com/SAGUARO-MMA/saguaro_tom/tree/b2e812c849ddbc646deef6ef4a7af39a0eac65c2) and [Hermes](https://github.com/LCOGT/hermes/tree/dev).

2023-11-28 15:04 UTC, phycodurus requested changes

2023-11-28 15:04 UTC, phycodurus commented on tom_tns/tns_report.py
If this is the module where all interaction with the TNS is done, then a convention I've used for swift and panstarrs is XXX_api.py . So, it's not a big deal but we might consider renaming this file to tns_api.py

2023-11-28 15:04 UTC, phycodurus commented on tom_tns_base/__init__.py
This files make it convenient to develop and debug the INSTALLED_APP, but are not strictly necessary and probably shouldn't be in the repo (although we've left them in other repos, for example in `tom_nonlocalizedevents`.

2023-11-28 21:20 UTC, jchate6 commented on pyproject.toml
Please check that this was done correctly?

2023-11-28 21:37 UTC, jchate6 commented on tom_tns_base/__init__.py
I'd rather leave this in for now unless you feel particularly strongly about it.

2023-12-14 18:36 UTC, phycodurus approved these changes

2023-12-14 18:36 UTC, merged